// Exibir todas as categorias

GET http://localhost:3000/api/v1/categoria

###
GET https://financas-app-backend-one.vercel.app/api/v1/categoria

###
// Gravar uma categoria
POST http://localhost:3000/api/v1/categoria
content-type: application/json

{
    "nome": "internettttt",
    "tipo": "despesa",
    "ativo": "true"
}

###
// Deletar uma categoria
DELETE http://localhost:3000/api/v1/categoria/14


###
// Atualizar uma categoria
PUT http://localhost:3000/api/v1/categoria/35
content-type: application/json

{
    "nome": "aluguel-testeeeeex ",
    "tipo": "receita",
    "ativo": "true"
}

###