// ERealizar login

// login
POST http://localhost:3000/api/v1/login
content-type: application/json

{
    "login": "jonas",
    "senha": "jonas@123"
}

###

// login vercel
POST https://financas-app-backend-one.vercel.app/api/v1/login
content-type: application/json

{
    "login": "jonas",
    "senha": "jonas@123"
}


###

// teste vercel
GET https://financas-app-backend-one.vercel.app/api/v1/teste


###

// teste vercel
GET http://localhost:3000/api/v1/teste