

https://platform.senior.com.br/t/senior.com.br/sam/1.0/monitoring/manager/status
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibG9naW4iOiJqb25hcyIsImlhdCI6MTc5MDk2MjkyMiwiZXhwIjoxNzkwOTkxNzIyfQ.i3effJV6waGrIFvfWfkgLqMaY0cRy9-1p85YJKS3Sw8