// Exibir todas os usuarios

GET http://localhost:3000/api/v1/usuario
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibG9naW4iOiJqb25hcyIsImlhdCI6MTc4OTg0MDQyNCwiZXhwIjoxNzg5ODY5MjI0fQ.AG_JAlKaQxCih6SW16Vey50EidXbibTH-i1DVUpFfCM


###
GET https://financas-app-backend-one.vercel.app/api/v1/usuario

###
// Gravar um usuario
POST http://localhost:3000/api/v1/usuario
content-type: application/json

{
    "nome": "teste do teste",
    "login": "teste",
    "email": "jonasbfranco@gmail.com",
    "senha": "jonas@123"
}

###
// Deletar uma usuario
DELETE http://localhost:3000/api/v1/usuario/5


###
// Atualizar um usuario
PUT http://localhost:3000/api/v1/usuario/1
content-type: application/json

{
    "nome": "jonas baptista francoo",
    "login": "jonass",
    "email": "jonasbfranco@gmail.com",
    "ativo": "true",
    "senha": ""
}

###